# Generated by Django 5.1 on 2024-08-25 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdid', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('fees', models.IntegerField(default=0)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('joindate', models.DateField()),
                ('payment_amount', models.IntegerField(default=0)),
                ('slot1', models.IntegerField(default=0)),
                ('slot2', models.IntegerField(default=0)),
                ('slot3', models.IntegerField(default=0)),
                ('slot1date', models.DateField()),
                ('slot2date', models.DateField()),
                ('slot3date', models.DateField()),
                ('pending', models.IntegerField(default=0)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademyApp.course')),
                ('student_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademyApp.type')),
            ],
        ),
    ]
